---
title: "Comparing the Changing Prevalence of Different Types of Crimes in LA County Before and During the COVID-19 Pandemic"
author: "Kaila An"
date: 11/27/2022
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

**Download the whole HTML report:**
**HTML REPORT** [**click here**]()

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px")
```


## Description

The COVID-19 pandemic had changed the world as we knew it like no other occurrence before. It changed people’s lifestyles, their habits, and overall created a “new normal”. People’s mindsets and priorities have changed so drastically, that it would be interesting to note whether or not it brought a change to criminal behavior and activity. For this project, I chose to focus on Los Angeles City Data, specifically, ‘Crime Data in LA from 2020 to present’ and ‘Crime Data in LA from 2010 to 2019’. These particular data sets document incidents of crime, transcribed from crime reports. This data has been provided by the Los Angeles Police Department. Based on these data sets, the question I would like to address is:

How has the prevalence of certain types of crimes in Los Angeles changed since the start of the COVID-19 pandemic?


# Read in the data
crime201019 <- data.table::fread("crimedata_2010to2019.csv")
crime202022 <- data.table::fread("crimedata_2020topresent.csv")
```

#Checking the Data



## Top 5 Crime Types
#For the period of 2010-19 (pre-pandemic) and the period of 2020-present (during the pandemic)











<br>

### Premise vs. Crime










